cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'fpp'
brew 'jq'
brew 'mas'
brew 'openssl'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'roundup'
brew 'tmux'
brew 'zsh'
brew 'zsh-completions'

cask 'font-sourcecodepro-nerd-font-mono'
cask 'font-ubuntu-nerd-font-mono'
cask 'font-ubuntumono-nerd-font-mono'

cask 'ccleaner'
cask 'dotnet-sdk'
cask 'enpass'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'postman'
cask 'rescuetime'
cask 'slack'
cask 'spotify'
cask 'toggl'
cask 'tunnelbear'
cask 'visual-studio-code'
cask 'vlc'
