cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'azure-cli'
brew 'bash-completion'
brew 'coreutils'
brew 'fzf'
brew 'git'
brew 'go'
brew 'grc'
brew 'jp2a'
brew 'jq'
brew 'kubectx'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'shpotify'
brew 'spaceman-diff'
brew 'speedtest-cli'
brew 'tmux'
brew 'unrar'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'google-chrome'
cask 'handbrake'
cask 'iterm2'
cask 'slack'
cask 'spotify'
cask 'transmission' 
cask 'visual-studio-code'
cask 'vlc'
