#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

echo "› which installers are running"
find . -name install.sh | while read installer ; do ls -l "${installer}" ; done

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done


if [ ! -x "$HOME/.vimrc" ]; then
  echo "› installing vim plugins"
  vim +PluginInstall +qall
fi
